services:
  - type: web
    name: prism-mb
    runtime: python
    pythonVersion: "3.11.7"
    rootDir: webapp
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true